version: '3.7'

services:
  data-science:
    container_name: data-science
    image: bfa1trung/notebook:latest
    volumes:
      - ./work:/home/jupyter/work
    ports:
      - "8889:8888"
    environment:
      - JUPYTER_TOKEN=password
