version: '3.3'

services:
  ui_container:
    container_name: ui_container
    image: bfa1trung/mvc:latest
    volumes:
      - img-volume:/app/wwwroot/img
      - json-volume:/app/wwwroot/json
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development


  algo_container:
    container_name: algo_container
    image: bfa1trung/notebook:latest
    #image: local.notebook
    #build: 
      #context: work
      #dockerfile: Dockerfile
    volumes:
      - ./work:/home/jupyter/work:ro
      - img-volume:/home/jupyter/mvc/wwwroot/img
      - json-volume:/home/jupyter/mvc/wwwroot/json
    ports:
      - "8889:8888"
    environment:
      - JUPYTER_TOKEN=password
volumes:
     img-volume:
     json-volume: 
