version: '3.7'

services:
  algo_container:
    container_name: algo_container
    image: bfa1trung/notebook:latest
    volumes:
      - ./work:/home/jupyter/work
    ports:
      - "8889:8888"
    environment:
      - JUPYTER_TOKEN=password
